name: check
on:
  pull_request:
  push:
      branches:
        - main

jobs:
  cargo-check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        features: ["location", "text", "location,text"]

    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile:   minimal
          override:  true

      - name: Check in vanilla
        uses: actions-rs/cargo@v1
        with:
          command: check

      - name: Check with features
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --features ${{ matrix.features }}
